service: tasks-management
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:660828509387:table/task

functions:
  CreateTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
resources:
  Resources:
    task:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: task
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
